{{- $environments := .Values.jxRequirements.environments }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  {{- range $environments }}
  {{- if and .ingress.tls.enabled .ingress.domain .ingress.tls.production }}
  name: "tls-{{ .ingress.domain | replace "." "-" }}-p"
  labels:
    jenkins.io/letsencrypt-service: production
spec:
  secretName: "tls-{{ .ingress.domain | replace "." "-" }}-p"
  issuerRef:
    name: letsencrypt-prod
  commonName: "*.{{ .ingress.domain }}"
  dnsNames:
  - "*.{{ .ingress.domain }}"
  {{- end }}
  {{- end }}
