{{- $provider := .Values.jxRequirements.cluster.provider }}
{{- $projectID := .Values.jxRequirements.cluster.projectID }}
{{- $environments := .Values.jxRequirements.environments }}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- range $environments }}
    {{- if and .ingress.tls.enabled (not .ingress.tls.production) .ingress.domain }}
    email: "{{ .ingress.tls.email }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsNames:
        - "*.{{ .ingress.domain }}"
        - "{{ .ingress.domain }}"
      # ACME DNS-01 provider configurations
      dns01:
        {{- if eq $provider "gke" }}
        clouddns:
          # The project in which to update the DNS zone
          project: "{{ $projectID }}"
          # A secretKeyRef to a google cloud json service account
          serviceAccountSecretRef:
            name: external-dns-gcp-sa
            key: credentials.json
        {{- else if eq $provider "eks" }}
        route53:
          region: {{ .Values.jxRequirements.cluster.region }}
        {{- end }}
    {{- end }}
    {{- end }}
